[build]
 publish = "public"
 command = "hugo -t jiafei_cactus"

[context.production.environment]
 HUGO_VERSION = "0.74.0"
 HUGO_ENV = "production"
 HUGO_ENABLEGITINFO = "true"

[context.split1]
 command = "hugo -t jiafei_cactus --enableGitInfo"

[context.split1.environment]
 HUGO_VERSION = "0.74.0"
 HUGO_ENV = "production"

[context.deploy-preview]
 command = "hugo -t jiafei_cactus --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
 HUGO_VERSION = "0.74.0"

[context.branch-deploy]
 command = "hugo -t jiafei_cactus -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
 HUGO_VERSION = "0.74.0"

[context.next.environment]
 HUGO_ENABLEGITINFO = "true"
